  spring:

    # Application Name
    application:
      name: nexus-platform

    datasource:

      # Employee Database (MySQL)
      employee:

        # Database URL
        url: jdbc:mysql://localhost:3306/employeesdb

        # Database Username
        username: ${DB_EMPLOYEE_USERNAME}

        # Database Password
        password: ${DB_EMPLOYEE_PASSWORD}

        # JDBC Driver
        driver-class-name: com.mysql.cj.jdbc.Driver

      # Department Database (PostgreSQL)
      department:

        # Database URL
        url: jdbc:postgresql://localhost:5432/departmentsdb

        # Database Username
        username: ${DB_DEPARTMENT_USERNAME}

        # Database Password
        password: ${DB_DEPARTMENT_PASSWORD}

        # JDBC Driver
        driver-class-name: org.postgresql.Driver

    jpa:

      hibernate:

        # Hibernate DDL Strategy
        #
        # create       -> Recreates schema on every startup (DATA LOSS)
        # create-drop  -> Creates schema on startup and drops on shutdown (DATA LOSS)
        # update       -> Updates schema and preserves existing data
        # validate     -> Validates schema against entities only
        # none         -> Disables Hibernate schema management
        #
        # Development  -> update
        # Production   -> validate + Flyway
        ddl-auto: update

      # Prints generated SQL queries
      show-sql: true

      properties:
        hibernate:

          # Formats SQL for readability
          format_sql: true

          # Highlights SQL in console
          highlight_sql: true

          # Adds comments before generated SQL
          use_sql_comments: true

  # Embedded Tomcat Configuration
  server:

    # Application Port
    port: 9191

  # Generated SQL Queries
  #
  # Shows actual SQL generated by Hibernate
  # Query Parameter Values
  #
  # Shows values bound to SQL parameters
  # JPA Lifecycle Logs
  #
  # Shows EntityManager / Transaction lifecycle logs
  # Logging Levels
  #
  # TRACE -> Most detailed logging
  # DEBUG -> Development debugging
  # INFO  -> Business events
  # WARN  -> Recoverable issues
  # ERROR -> Application failures

  logging:
    level:
      # Generated SQL Queries
      org.hibernate.SQL: DEBUG
      # Query Parameter Values
      org.hibernate.orm.jdbc.bind: TRACE
      # JPA Lifecycle Logs
      org.springframework.orm.jpa: DEBUG
      root: INFO
      com.raina.nexus: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  # ==========================================================
  # External Third Party APIs
  # ==========================================================

  external:

    weather:
      # Create Free Account:
      # https://www.weatherapi.com/signup.aspx
      # API Documentation:
      # https://www.weatherapi.com/docs/
      # Weather API Base URL
      base-url: https://api.weatherapi.com/v1
      # Weather API Key
      api-key: ${WEATHER_API_KEY}